# Generated by Django 6.0 on 2025-12-28 08:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatars/default-avatar', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
